import { resolveAppConfig } from "./config.mjs";
import { createNavigationButtons, createFeatureCard } from "./fieldwise-ui.mjs";

const params = new URLSearchParams(location.search);
const appId = params.get("app") || "core";
const config = resolveAppConfig(appId);
let activeTab = config.tabs[0][0];
const desktop=window.fieldwiseDesktop;
const geo=desktop?.biology;
const auth=desktop?.auth;
let investigation=null;
let profile=null;
let workspaceStarted=false;
const storageKey="biology-active-investigation";

document.documentElement.style.setProperty("--accent", config.accent);
document.documentElement.style.setProperty("--accent-dark", config.accentDark);
document.title = config.name;

const nav = document.querySelector("#nav");
const cards = document.querySelector("#cards");
const title = document.querySelector("#app-title");
const eyebrow = document.querySelector("#eyebrow");
const welcome = document.querySelector("#welcome");
const pageTitle = document.querySelector("#page-title");

title.textContent = config.name;
eyebrow.textContent = config.eyebrow;
welcome.textContent = config.welcome;

const authRoot=document.querySelector("#auth-root"),appShell=document.querySelector("#app-shell"),teacherForm=document.querySelector("#teacher-form"),studentForm=document.querySelector("#student-form");
function showAuthError(error){document.querySelector("#auth-error").textContent=error?.message||String(error||"");}
function selectRole(role){const teacher=role==="teacher";teacherForm.hidden=!teacher;studentForm.hidden=teacher;document.querySelector("#teacher-role").classList.toggle("active",teacher);document.querySelector("#student-role").classList.toggle("active",!teacher);showAuthError("");}
function showAuth(){profile=null;appShell.hidden=true;authRoot.hidden=false;}
async function showApp(nextProfile){profile=nextProfile;authRoot.hidden=true;appShell.hidden=false;document.querySelector("#profile-name").textContent=profile.displayName;document.querySelector("#profile-role").textContent=`${profile.role==="teacher"?"Teacher":"Student"} workspace · Offline ready`;document.querySelector("#profile-avatar").textContent=(profile.displayName||"F").slice(0,1).toUpperCase();if(!workspaceStarted){workspaceStarted=true;await startWorkspace();}}

function renderNavigation() {
  nav.replaceChildren(...createNavigationButtons(config.tabs, activeTab, (id) => { activeTab = id; renderNavigation(); renderCards(); }));
}

function fallbackCards() {
  const current = config.tabs.find(([id]) => id === activeTab);
  pageTitle.textContent = current?.[1] || "Home";
  const matching = config.cards.filter(([, , route]) => route === activeTab);
  const visible = matching.length ? matching : config.cards;
  cards.replaceChildren(...visible.map(([heading, description, route]) => createFeatureCard({ heading, description, onAction:() => { activeTab=route; renderNavigation(); renderCards(); } })));
}
async function persist(){investigation.updatedAt=new Date().toISOString();await desktop.save(storageKey,investigation);}
function section(title,description=""){const node=document.createElement("section");node.className="geo-panel";const head=document.createElement("div");head.className="geo-panel-head";head.innerHTML="<h3></h3><p></p>";head.querySelector("h3").textContent=title;head.querySelector("p").textContent=description;node.append(head);return node;}
async function renderActivity(){cards.replaceChildren();if(!investigation){const panel=section("Start an investigation","Choose a ready-made inquiry or open an assignment from FieldWise Core.");const grid=document.createElement("div");grid.className="template-grid";for(const item of await geo.templates()){grid.append(createFeatureCard({heading:item.title,description:item.question,onAction:async()=>{investigation=await geo.newInvestigation(item.id,{});await persist();renderCards();}}));}panel.append(grid);cards.append(panel);return;}const progress=await geo.progress(investigation);const panel=section(investigation.title,investigation.activityId?`Core activity ${investigation.activityId}`:"Independent local investigation");panel.innerHTML+=`<div class="progress-summary"><strong>${progress.percentage}%</strong><span>${progress.count} of 8 inquiry stages</span><div><i style="width:${progress.percentage}%"></i></div></div>`;const stages=document.createElement("div");stages.className="stage-strip";for(const [id,done] of Object.entries(progress.complete)){const badge=document.createElement("span");badge.className=done?"done":"";badge.textContent=id;stages.append(badge);}panel.append(stages);const actions=document.createElement("div");actions.className="geo-actions";actions.innerHTML=`<button class="primary continue">Continue inquiry</button><button class="secondary new">New investigation</button>`;actions.querySelector(".continue").addEventListener("click",()=>{activeTab="tools";renderNavigation();renderCards();});actions.querySelector(".new").addEventListener("click",async()=>{if(!confirm("Replace the active local investigation?"))return;await desktop.save(storageKey,null);investigation=null;renderCards();});panel.append(actions);cards.append(panel);}
async function renderTools(){
  cards.replaceChildren();if(!investigation)return renderActivity();const panel=section("Biological investigation","Plan variables, replication, method and traceable evidence.");
  const fields={question:"Investigable question",hypothesis:"Hypothesis",independentVariable:"Independent variable",dependentVariable:"Dependent variable",controlledVariables:"Controlled variables",method:"Method and sampling design",explanation:"Biological explanation",evaluation:"Uncertainty, limitations and alternatives",conclusion:"Evidence-based conclusion"};for(const [name,label] of Object.entries(fields)){const field=document.createElement("label");field.textContent=label;const input=document.createElement("textarea");input.rows=name==="method"?5:3;input.value=investigation[name]||"";input.addEventListener("input",async()=>{investigation[name]=input.value;await persist();});field.append(input);panel.append(field);}const replicate=document.createElement("label");replicate.textContent="Planned replicates or sampling units";const replicateInput=document.createElement("input");replicateInput.type="number";replicateInput.min="1";replicateInput.value=investigation.plannedReplicates||1;replicateInput.addEventListener("input",async()=>{investigation.plannedReplicates=Number(replicateInput.value);await persist();});replicate.append(replicateInput);panel.append(replicate);
  investigation.safetyEthics||={teacherCheckpoint:false,organismHandlingAcknowledged:false,specimenApproved:false,consentValid:false,nonDiagnosticAcknowledged:false,notes:""};const gate=section("Safety and ethics","Teacher approval remains authoritative for collection, specimens, handling and consent.");const notes=document.createElement("label");notes.textContent="Safety, ethics and consent controls";const noteInput=document.createElement("textarea");noteInput.rows=4;noteInput.value=investigation.safetyEthics.notes||"";noteInput.addEventListener("input",async()=>{investigation.safetyEthics.notes=noteInput.value;await persist();});notes.append(noteInput);gate.append(notes);const checks=[["teacherCheckpoint","Teacher safety and ethics checkpoint completed"]];if(investigation.templateId==="ecology")checks.push(["organismHandlingAcknowledged","Boundaries, organism handling and location permissions acknowledged"]);if(investigation.templateId==="microscopy")checks.push(["specimenApproved","Specimen, stain and glass-handling procedure approved"]);if(investigation.templateId==="physiology")checks.push(["consentValid","Consent-valid or fictional data confirmed"],["nonDiagnosticAcknowledged","Non-diagnostic educational use acknowledged"]);for(const [name,label] of checks){const row=document.createElement("label");row.className="check-field";const input=document.createElement("input");input.type="checkbox";input.checked=Boolean(investigation.safetyEthics[name]);input.addEventListener("change",async()=>{investigation.safetyEthics[name]=input.checked;await persist();});row.append(input,document.createTextNode(label));gate.append(row);}cards.append(panel,gate);
}
function activeSite(){return investigation?.sites?.[0];}
async function renderMap(){cards.replaceChildren();if(!investigation)return renderActivity();const panel=section("Spatial workspace","Record coordinates for each site. The offline plot updates without map tiles.");const strip=document.createElement("div");strip.className="site-strip";for(const [index,site] of investigation.sites.entries()){const button=document.createElement("button");button.innerHTML=`<strong></strong><span></span>`;button.querySelector("strong").textContent=site.name;button.querySelector("span").textContent=site.latitude!==""?`${site.latitude}, ${site.longitude}`:"No coordinates";button.addEventListener("click",()=>{investigation.sites.unshift(investigation.sites.splice(index,1)[0]);renderMap();});strip.append(button);}const site=activeSite();const form=document.createElement("form");form.className="geo-panel coordinate-form";form.innerHTML=`<div class="field-row"><label>Site name<input name="name"></label><label>Recorded at<input name="recordedAt" type="datetime-local"></label></div><div class="field-row"><label>Latitude<input name="latitude" type="number" step="any"></label><label>Longitude<input name="longitude" type="number" step="any"></label></div><label>Site observations<textarea name="notes" rows="5"></textarea></label><div class="geo-actions"><button type="button" class="secondary location">Use current location</button><button type="button" class="secondary weather">Load current weather</button><button type="button" class="primary add-site">+ Add site</button></div><div class="weather-result"></div>`;for(const name of ["name","recordedAt","latitude","longitude","notes"])form.elements[name].value=site[name]||"";form.addEventListener("input",async event=>{if(event.target.name){site[event.target.name]=event.target.value;await persist();}});form.querySelector(".add-site").addEventListener("click",async()=>{investigation.sites.unshift(await geo.newSite(investigation.sites.length+1));await persist();renderMap();});form.querySelector(".location").addEventListener("click",()=>navigator.geolocation.getCurrentPosition(async({coords})=>{site.latitude=coords.latitude.toFixed(6);site.longitude=coords.longitude.toFixed(6);await persist();renderMap();},error=>alert(error.message),{enableHighAccuracy:true}));form.querySelector(".weather").addEventListener("click",async()=>{try{const data=await geo.weather(site.latitude,site.longitude);site.weather=data;await persist();form.querySelector(".weather-result").textContent=`${data.current.temperature_2m}${data.units.temperature_2m} · wind ${data.current.wind_speed_10m}${data.units.wind_speed_10m} · ${data.suitability.label}: ${data.suitability.reason}`;}catch(error){form.querySelector(".weather-result").textContent=error.message;}});panel.append(strip,form);cards.append(panel);}
async function renderData(){cards.replaceChildren();if(!investigation)return renderActivity();const site=activeSite(),template=(await geo.templates()).find(x=>x.id===investigation.templateId);const panel=section(`Measurements · ${site.name}`,"Record values with units and provenance so data quality remains visible.");const form=document.createElement("form");form.className="measurement-form";form.innerHTML=`<select name="fieldId"></select><input name="rawValue" required placeholder="Value"><input name="unit" placeholder="Unit"><select name="origin"><option>measured</option><option>estimated</option><option>imported</option></select><input name="source" placeholder="Device or source"><button class="primary">Record</button>`;for(const field of template.fields)form.elements.fieldId.add(new Option(field[1],field[0]));form.elements.fieldId.addEventListener("change",()=>{const field=template.fields.find(x=>x[0]===form.elements.fieldId.value);form.elements.unit.value=field?.[3]||"";});form.elements.fieldId.dispatchEvent(new Event("change"));form.addEventListener("submit",async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));const field=template.fields.find(x=>x[0]===values.fieldId);site.measurements.push(await geo.addMeasurement({...values,label:field?.[1]}));form.reset();await persist();renderData();});panel.append(form);const table=document.createElement("div");table.className="measurement-list";for(const item of site.measurements){const row=document.createElement("article");row.innerHTML=`<strong></strong><span></span><small></small>`;row.querySelector("strong").textContent=item.label;row.querySelector("span").textContent=`${item.rawValue} ${item.unit}`;row.querySelector("small").textContent=`${item.origin}${item.source?` · ${item.source}`:""}`;table.append(row);}panel.append(table);cards.append(panel);}
async function renderEvidence(){cards.replaceChildren();if(!investigation)return renderActivity();const readiness=await geo.readiness(investigation),panel=section("Evidence & Core submission",readiness.ready?"This investigation meets the MVP submission checks.":"Resolve the blockers before returning work to Core.");const summary=document.createElement("div");summary.className="readiness-box";summary.innerHTML=`<strong>${readiness.progress.percentage}% inquiry complete</strong><span>${readiness.evidence} evidence records</span>`;panel.append(summary);for(const blocker of readiness.blockers){const p=document.createElement("p");p.className="blocker";p.textContent=blocker;panel.append(p);}const site=activeSite();const files=document.createElement("div");files.className="attachment-list";for(const item of site.attachments){const row=document.createElement("article");row.textContent=`${item.name} · ${Math.ceil(item.size/1024)} KB`;files.append(row);}const attach=document.createElement("button");attach.className="secondary";attach.textContent="Attach evidence";attach.addEventListener("click",async()=>{const result=await desktop.importAttachment(investigation.id);if(!result.canceled){site.attachments.push(result.attachment);await persist();renderEvidence();}});const submit=document.createElement("button");submit.className="primary";submit.textContent="Queue submission and return to Core";submit.disabled=!readiness.ready;submit.addEventListener("click",async()=>{try{const receipt=await geo.submitToCore(investigation);investigation.status=receipt.status;await persist();}catch(error){alert(error.message);}});const actions=document.createElement("div");actions.className="geo-actions";actions.append(attach,submit);panel.append(files,actions);cards.append(panel);}
async function renderAnalysis(){if(!investigation)return;const template=(await geo.templates()).find(item=>item.id===investigation.templateId),analysis=section("Basic analysis across sites","Numeric fields are summarised using sample count, mean and range.");let count=0;for(const field of template.fields){const values=investigation.sites.flatMap(site=>site.measurements||[]).filter(item=>item.fieldId===field[0]&&item.numericValue!==null).map(item=>item.numericValue);if(!values.length)continue;count+=1;const row=document.createElement("p");row.textContent=`${field[1]}: n=${values.length}, mean ${(values.reduce((sum,value)=>sum+value,0)/values.length).toFixed(2)}${field[3]?` ${field[3]}`:""}, range ${Math.min(...values)}–${Math.max(...values)}`;analysis.append(row);}if(!count){const empty=document.createElement("p");empty.textContent="Record numeric measurements to calculate means and ranges.";analysis.append(empty);}cards.append(analysis);}
async function renderCards(){const current=config.tabs.find(([id])=>id===activeTab);pageTitle.textContent=current?.[1]||"Activity";if(activeTab==="activity")return renderActivity();if(activeTab==="tools")return renderBiologyInvestigations();if(activeTab==="map")return renderBiologyTools();if(activeTab==="data")return renderBiologyEvidence();if(activeTab==="evidence")return renderBiologyPortfolio();return fallbackCards();}

async function capturePhoto(){if(!investigation)return alert("Start an investigation first.");let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});const dialog=document.createElement("dialog");dialog.className="fw-dialog camera-dialog";dialog.innerHTML=`<h2>Capture field evidence</h2><video autoplay playsinline></video><canvas hidden></canvas><div class="geo-actions"><button class="secondary cancel">Cancel</button><button class="primary capture">Take photo</button></div>`;document.body.append(dialog);const video=dialog.querySelector("video");video.srcObject=stream;const close=()=>{stream.getTracks().forEach(track=>track.stop());dialog.close();dialog.remove();};dialog.querySelector(".cancel").addEventListener("click",close);dialog.querySelector(".capture").addEventListener("click",async()=>{const canvas=dialog.querySelector("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.9));if(!blob)throw new Error("The camera frame could not be encoded.");const attachment=await desktop.saveCapture(investigation.id,{bytes:new Uint8Array(await blob.arrayBuffer()),mimeType:blob.type,name:`${activeSite().name} camera.jpg`});activeSite().attachments.push(attachment);await persist();close();if(activeTab==="evidence")renderEvidence();});dialog.showModal();}catch(error){stream?.getTracks().forEach(track=>track.stop());alert(`Camera unavailable: ${error.message}`);}}
function setupExports(){const actions=document.createElement("div");actions.className="geo-actions";const camera=document.createElement("button");camera.className="secondary";camera.textContent="Camera";camera.addEventListener("click",capturePhoto);const csv=document.createElement("button");csv.className="secondary";csv.textContent="Export measurements CSV";csv.addEventListener("click",async()=>{if(!investigation)return alert("Start an investigation first.");await desktop.exportText({format:"csv",suggestedName:`${investigation.title}_Measurements`,content:await geo.measurementsCsv(investigation)});});const report=document.createElement("button");report.className="secondary";report.textContent="Export report";report.addEventListener("click",async()=>{if(!investigation)return alert("Start an investigation first.");await desktop.exportText({format:"txt",suggestedName:`${investigation.title}_Report`,content:await geo.report(investigation)});});const print=document.createElement("button");print.className="secondary";print.textContent="Print / Save PDF";print.addEventListener("click",()=>window.print());actions.append(camera,csv,report,print);document.querySelector(".topbar button")?.remove();document.querySelector(".topbar").append(actions);}

async function startWorkspace(){investigation=await desktop.load(storageKey);const accept=async context=>{if(!context)return;investigation=await geo.newInvestigation("ecology",context);await persist();activeTab="activity";renderNavigation();renderCards();};geo.onLaunchContext(accept);await accept(await geo.takeLaunchContext());setupExports();renderNavigation();renderCards();}
document.querySelector("#teacher-role").addEventListener("click",()=>selectRole("teacher"));
document.querySelector("#student-role").addEventListener("click",()=>selectRole("student"));
teacherForm.addEventListener("submit",async event=>{event.preventDefault();showAuthError("");try{await showApp(await auth.teacherSignIn(Object.fromEntries(new FormData(teacherForm))));}catch(error){showAuthError(error);}});
studentForm.addEventListener("submit",async event=>{event.preventDefault();showAuthError("");try{await showApp(await auth.studentJoin(Object.fromEntries(new FormData(studentForm))));}catch(error){showAuthError(error);}});
document.querySelector("#sign-out").addEventListener("click",async()=>{await auth.signOut();showAuth();});
async function boot(){if(!geo||!auth)throw new Error("The packaged desktop bridge could not be loaded.");const status=await auth.status();for(const year of status.yearLevels)studentForm.elements.yearLevel.add(new Option(year,year));const session=await auth.session();session.profile?await showApp(session.profile):showAuth();}
boot().catch(error=>{showAuth();showAuthError(error);});

function normalizeBiologyWorkspace(){investigation.biologyRecords||=[];}
function biologyRecordList(records=investigation.biologyRecords){const list=document.createElement("div");list.className="measurement-list";for(const item of records){const row=document.createElement("article");row.innerHTML="<strong></strong><span></span><small></small>";row.querySelector("strong").textContent=item.siteName||item.specimen||item.observedName||item.traitName||item.participantAnonID||item.species||item.kind;row.querySelector("span").textContent=item.kind;row.querySelector("small").textContent=String(item.dateRecorded||item.createdAt||"").slice(0,10);list.append(row);}return list;}
function biologyFormPanel(title,description,html,create){const panel=section(title,description),form=document.createElement("form");form.className="biology-form";form.innerHTML=html;form.addEventListener("submit",async event=>{event.preventDefault();try{const value=await create(form,Object.fromEntries(new FormData(form)));investigation.biologyRecords.push(value);await persist();renderCards();}catch(error){alert(error.message);}});panel.append(form);return panel;}
async function renderBiologyInvestigations(){cards.replaceChildren();if(!investigation)return renderActivity();normalizeBiologyWorkspace();const catalog=await geo.recordCatalog();
  const ecology=biologyFormPanel("Ecology sampling","Record a site, quadrat design and traceable species observation.",`<label>Site name<input name="siteName" required></label><label>Habitat notes<input name="habitatNotes"></label><label>Sampling design<select name="samplingDesign">${catalog.samplingDesigns.map(value=>`<option>${value}</option>`).join("")}</select></label><label>Quadrat size (m²)<input name="quadratSizeM2" type="number" step="any" value="1"></label><label>Recorder<input name="recorderName" required></label><label>Species observed<input name="speciesName" required></label><label>Native status<select name="nativeStatus">${catalog.nativeStatuses.map(value=>`<option>${value}</option>`).join("")}</select></label><label>Individuals counted<input name="countOfIndividuals" type="number" min="0"></label><label>Cover (%)<input name="coverPercent" type="number" min="0" max="100"></label><button class="primary">Save ecology record</button>`,(form,values)=>geo.newEcologyRecord({...values,observations:[{speciesName:values.speciesName,nativeStatus:values.nativeStatus,countOfIndividuals:values.countOfIndividuals,coverPercent:values.coverPercent}]}));
  const plant=biologyFormPanel("Plant trial","Record a treatment/replicate combination and its latest growth measurement.",`<label>Species<input name="species" required></label><label>Treatment<input name="treatmentName" value="Control"></label><label>Replicate<input name="replicateNumber" type="number" min="1" value="1"></label><label>Growth stage<input name="growthStage"></label><label>Height (mm)<input name="heightMm" type="number" step="any"></label><label>Leaf count<input name="leafCount" type="number" min="0"></label><label>Environmental notes<textarea name="environmentalNotes"></textarea></label><button class="primary">Save plant trial</button>`,(form,values)=>geo.newPlantTrial({...values,measurements:[{heightMm:values.heightMm,leafCount:values.leafCount,dateRecorded:new Date().toISOString()}]}));cards.append(ecology,plant,biologyRecordList(investigation.biologyRecords.filter(item=>["ecology","plant"].includes(item.kind))));}
async function renderBiologyTools(){cards.replaceChildren();if(!investigation)return renderActivity();normalizeBiologyWorkspace();const catalog=await geo.recordCatalog();
  const microscopy=biologyFormPanel("Microscopy and scale","Store specimen context and calculate a calibrated size estimate.",`<label>Specimen<input name="specimen" required></label><label>Stain<input name="stain"></label><label>Magnification<input name="magnification" type="number" value="400" required></label><label>Field of view (µm)<input name="fieldOfViewMicrons" type="number" value="450" required></label><label>Structure fraction (0–1)<input name="estimatedFraction" type="number" min="0" max="1" step="any"></label><label>Calibration notes<textarea name="calibrationNotes"></textarea></label><button class="primary">Save microscopy record</button>`,(_form,values)=>geo.newMicroscopyRecord(values));
  const taxonomy=biologyFormPanel("Identification and taxonomy","Retain the observed identity, classification, evidence source and confidence.",`<label>Observed organism<input name="observedName" required></label><label>Kingdom<input name="kingdom"></label><label>Phylum<input name="phylum"></label><label>Class<input name="className"></label><label>Order<input name="order"></label><label>Family<input name="family"></label><label>Genus<input name="genus"></label><label>Species<input name="species"></label><label>Identifying features<textarea name="identifyingFeatures"></textarea></label><label>Source or field key<input name="source"></label><button class="primary">Save identification</button>`,(_form,values)=>geo.newTaxonomyRecord(values));
  const genetics=biologyFormPanel("Genetics cross","Validate parent genotypes and retain observed phenotype counts.",`<label>Trait<input name="traitName" required></label><label>Cross type<select name="crossType"><option value="monohybrid">Monohybrid</option><option value="dihybrid">Dihybrid</option></select></label><label>Parent A genotype<input name="parentAGenotype" value="Aa" required></label><label>Parent B genotype<input name="parentBGenotype" value="Aa" required></label><label>Observed counts (comma-separated)<input name="observedCounts"></label><label>Notes<textarea name="notes"></textarea></label><button class="primary">Save genetics cross</button>`,(_form,values)=>geo.newGeneticsCross({...values,observedPhenotypeCounts:values.observedCounts.split(",").filter(Boolean).map(Number)}));
  const physiology=biologyFormPanel("Anonymous physiology trial","Consent-valid, non-diagnostic educational measurements only.",`<label>Anonymous participant ID<input name="participantAnonID" required></label><label>Protocol<select name="protocolType">${catalog.physiologyProtocols.map(value=>`<option>${value}</option>`).join("")}</select></label><label>Recorded by<input name="recordedBy"></label><label>Measured value<input name="value" type="number" step="any"></label><label class="check-field"><input name="consentGiven" type="checkbox">Valid consent recorded</label><label class="check-field"><input name="nonDiagnosticAcknowledged" type="checkbox">Non-diagnostic educational use acknowledged</label><button class="primary">Save physiology trial</button>`,(form,values)=>geo.newPhysiologyTrial({...values,consentGiven:form.elements.consentGiven.checked,nonDiagnosticAcknowledged:form.elements.nonDiagnosticAcknowledged.checked,measurements:[{value:values.value,timestamp:new Date().toISOString()}]}));cards.append(microscopy,taxonomy,genetics,physiology,biologyRecordList(investigation.biologyRecords.filter(item=>!["ecology","plant"].includes(item.kind))));}
async function renderBiologyEvidence(){cards.replaceChildren();if(!investigation)return renderActivity();normalizeBiologyWorkspace();const panel=section("Biology evidence","Review specialist records alongside measurements, attachments and provenance.");const counts=Object.entries(investigation.biologyRecords.reduce((all,item)=>({...all,[item.kind]:(all[item.kind]||0)+1}),{}));if(!counts.length){const empty=document.createElement("p");empty.textContent="No specialist biology records yet.";panel.append(empty);}for(const [kind,count] of counts){const row=document.createElement("p");row.textContent=`${kind}: ${count}`;panel.append(row);}panel.append(biologyRecordList());await renderData();await renderAnalysis();cards.prepend(panel);}
async function renderBiologyPortfolio(){await renderEvidence();if(!investigation)return;normalizeBiologyWorkspace();const portfolio=await geo.portfolioSummary(investigation),panel=section("Biology portfolio","A consolidated view of investigations, specialist records and submission evidence."),summary=document.createElement("div");summary.className="portfolio-summary";const evidence=(investigation.sites||[]).reduce((sum,site)=>sum+(site.measurements?.length||0)+(site.attachments?.length||0),0);for(const [value,label] of [[portfolio.readyRecords,"report-ready specialist records"],[portfolio.measurements+portfolio.attachments,"measurement and media evidence"],[(investigation.sites||[]).length,"investigation sites"]]){const item=document.createElement("article");item.innerHTML="<strong></strong><span></span>";item.querySelector("strong").textContent=value;item.querySelector("span").textContent=label;summary.append(item);}panel.append(summary);cards.prepend(panel);}
